Add support for local decompression and conversion
tobfisch/openstack-image-manager pull request #1
Opened 2021-06-17 09:11 UTC by tobfisch

2021-06-17 09:58 UTC, sebastianriese requested changes

2021-06-17 09:58 UTC, sebastianriese commented on src/manage.py
> +import urllib.request
The code already imports `requests` requests should well be capable of doing the job of `urrlib.request`, so for the sake of the uniformity of the code `requests` should be preferred.

2021-06-17 09:58 UTC, sebastianriese commented on src/manage.py
> +    }
I think this lacks the ability to inject the image properties that may be required for the scheduler, they are probably added by the automated metadata injection in the image import task code path.

2021-06-17 09:58 UTC, sebastianriese commented on src/manage.py
> +        new_tmp_image = os.getcwd() + '/' + new_file_name
Please use `pathlib.Path.cwd() / new_file_name` or at list `os.path.join`. (Again I am not sure if using the cwd is the best option.)

2021-06-17 09:58 UTC, sebastianriese commented on src/manage.py
> +    return status
Please use a boolean `True`/`False` to support success failure, or, even better, raise an exception in the case of failure. The latter would be consistent with failures during the open stack API calls, which will certainly already raise exceptions.

2021-06-17 09:58 UTC, sebastianriese commented on src/manage.py
> +    with urllib.request.urlopen(url) as response, open(tmp_image, 'wb') as out_file:
The urllib call should be replaced with an equivalent requests call.

2021-06-17 15:02 UTC, sebastianriese commented on src/manage.py
> +    with urllib.request.urlopen(url) as response, open(tmp_image, 'wb') as out_file:
(Note: Ideally make sure that the download is streamed and not cached in memory, images can potentially be quite big, if it is cumbersome to replace the code with requests based code, then it is okay to keep urllib plus a comment why it is used instead of requests there.)

2021-06-17 15:19 UTC, tobfisch commented on src/manage.py
> +    with urllib.request.urlopen(url) as response, open(tmp_image, 'wb') as out_file:
I replaced the calls and also the download should also be streamed now to avoid caching the image in the memory.

2021-06-17 15:20 UTC, tobfisch commented on src/manage.py
> +        new_tmp_image = os.getcwd() + '/' + new_file_name
I changed it to `pathlib.Path.cwd()` instead of `os.getcwd()`.

2021-06-17 15:28 UTC, tobfisch commented on src/manage.py
> +    return status
I changed the return values to `True` and `False`. 
What exception should be thrown if an image creation fails?

2021-06-17 15:29 UTC, tobfisch commented on src/manage.py
> +import urllib.request
Changed the code to use `requests` and removed the `urllib.request` import.

2021-06-17 15:31 UTC, tobfisch commented on src/manage.py
> +    }
Which image properties should be additionally injected for the scheduler?

2021-06-18 13:32 UTC, sebastianriese commented on src/manage.py
> +            out_file.write(response.content)
This does not stream the content, `response.content` will always return all data as a bytes object (so all data will be cached in RAM). The correct solution seems to loop ovder `response.iter_content(chunk_size=None)`  and write the chunks <https://docs.python-requests.org/en/master/api/#requests.Response.iter_content>.

I am, however, not sure how how connection resets during the streaming of the contents are handled (if they just end the content iterator this would lead to silently truncated results).

2021-06-21 08:13 UTC, tobfisch commented on src/manage.py
> +            out_file.write(response.content)
I worked the `response.iter_content(chunk_size=None)` solution in. 

I would think connection reset would lead to exceptions like: `requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))`

2021-06-21 09:51 UTC, sebastianriese commented on src/manage.py
> +        'img_hv_type': 'kvm'
Missing commas (resulting in a SyntaxError). Also: Do we really want the images to have visibility `private`?

2021-06-21 13:08 UTC, sebastianriese commented on src/manage.py
> +    return status
That depends on the use of exceptions by the rest of the code, I'd say raising `RuntimeError` with a good error message should be a viable option. If the original code does not use exceptions for signalling (unless they are raised by the underlying libraries), continuing to use a return value may be a good solution.

(Sorry for the late reply).

2021-06-21 13:09 UTC, sebastianriese commented on src/manage.py
> +    logging.info("Downloading image for convertion and/or decompression: '%s'" % name)
Typo: convertion -> conversion.

2021-06-29 08:34 UTC, tobfisch commented on src/manage.py
> +    logging.info("Downloading image for convertion and/or decompression: '%s'" % name)
Fixed the typo.

2021-06-29 08:44 UTC, tobfisch commented on src/manage.py
> +        'img_hv_type': 'kvm'
I fixed the SyntaxError. 
The initial visibility is `private`, after successfully creating the image (and perhaps successfully testing it) the image visibility will be changed according to `image['visibility']` 
This way it can be prevented that users are seeing and maybe trying to use not working images.

2021-06-29 08:57 UTC, tobfisch commented on src/manage.py
> +    return status
I think the original code does not use exceptions as signalling and the Openstack libraries also only calling HTTP POST function call if I read the code correctly. 
I would stick with return values for now.

2021-06-29 10:14 UTC, sebastianriese requested changes

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +        logging.info("Unsupported file format, next image")
I think this log message is wrong.

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +            subprocess.call(["xzcat", tmp_image], stdout=uncompressed_file)
`subprocess.call` is [softly deprecated](https://docs.python.org/3/library/subprocess.html#older-high-level-api) and does not check the exit code of the process for success, but returns it instead.

You at least have the check the returned exit code to make sure that `xzcat` operated successfully.

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +        subprocess.run(["qemu-img", "convert", "-f", "qcow2", "-O", "raw",
This call does not check the return code, you can use the `check=True` keyword argument to make `subprocess.run` raise an exception for a non-zero exit code (Or check the exit code manually).

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +            subprocess.call(["xzcat", tmp_image], stdout=uncompressed_file)
(Another alternative would be to use the `lzma` module to work with the xz-data directly from python – I am not sure whether that would be faster or more memory efficient.)

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +    subprocess.run(['rm', tmp_image, tmp_image_raw])
File deletion should rather be done with built-in python means than by calling an external process. E.g. using https://docs.python.org/3/library/pathlib.html#pathlib.Path.unlink or https://docs.python.org/3/library/os.html#os.unlink

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +        subprocess.run(['rm', tmp_image])
File deletion should rather be done with built-in python means than by calling an external process. E.g. using https://docs.python.org/3/library/pathlib.html#pathlib.Path.unlink or https://docs.python.org/3/library/os.html#os.unlink

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +    tmp_image = str(pathlib.Path.cwd() / file_name)
The semantically correct conversion of paths to strings is to use `os.fspath`, if you keep the path as object and only pass it to subprocess calls as string, the code can be slightly simplified or made more consistent. (e.g. you can open a path with the `open` method – in recent python versions the built-in `open` and the functions from `os` also accept path-like objects in addition to strings).

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +    if file_name.endswith(".xz"):
These operations (working with the suffices) can be done semantically with the `.stem` and `.suffix` methods of `pathlib.Path`.

2021-06-29 10:14 UTC, sebastianriese commented on src/manage.py
> +    glance.images.upload(image.id, open(tmp_image_raw, 'rb'))
The opened file should be scoped by `with` while the `__del__` method of the file object will close the stream once the object looses its last reference, it is cleaner to make explicitly sure this happens.

2021-07-01 06:55 UTC, tobfisch commented on src/manage.py
> +    glance.images.upload(image.id, open(tmp_image_raw, 'rb'))
I reworked the command, so that the opened file is scoped by `with`.

2021-07-01 06:56 UTC, tobfisch commented on src/manage.py
> +        subprocess.run(['rm', tmp_image])
All file deletions are now done via `os.unlink`.

2021-07-01 07:27 UTC, tobfisch commented on src/manage.py
> +    subprocess.run(['rm', tmp_image, tmp_image_raw])
Fixed.

2021-07-01 07:28 UTC, tobfisch commented on src/manage.py
> +        subprocess.run(["qemu-img", "convert", "-f", "qcow2", "-O", "raw",
I added the `check=True` keyword.

2021-07-01 07:29 UTC, tobfisch commented on src/manage.py
> +            subprocess.call(["xzcat", tmp_image], stdout=uncompressed_file)
I replaced the `subprocess.call` with `subprocess.run` and also added the `check=True` keyword.

2021-07-01 07:29 UTC, tobfisch commented on src/manage.py
> +        logging.info("Unsupported file format, next image")
You are right. 
I fixed the log message and also added an additional check if the file format is really supported.

2021-07-01 07:31 UTC, tobfisch commented on src/manage.py
> +    tmp_image = str(pathlib.Path.cwd() / file_name)
I removed the conversion from path to strings completely.

2021-07-01 07:32 UTC, tobfisch commented on src/manage.py
> +    if file_name.endswith(".xz"):
I changed the if-conditions to work with these methods.

2021-07-02 09:25 UTC, sebastianriese commented on src/manage.py
> +    tmp_image = str(pathlib.Path.cwd() / file_name)
Cool that this works, I wouldn't have known that `subprocess.run` accepts path-like objects in argument lists, good to know (although there seem to have been lingering bugs for some time, at least on windows: <https://bugs.python.org/issue31961>, <https://bugs.python.org/issue41649> for Python versions before 3.8).

2021-07-02 09:36 UTC, sebastianriese approved these changes

2021-07-16 09:41 UTC, merged