Add support for testing images
tobfisch/openstack-image-manager pull request #2
Opened 2021-06-17 09:18 UTC by tobfisch

2021-06-17 09:38 UTC, sebastianriese requested changes

2021-06-17 09:38 UTC, sebastianriese commented on src/manage.py
> +        return 'failure'
Please return a boolean `True`/`False` instead of string constants as marker for success/failure.

2021-06-17 09:38 UTC, sebastianriese commented on src/manage.py
> +    test_process = subprocess.run(["ssh", "-o", "StrictHostKeyChecking no","-i", os.getcwd()+'/'+keypair_name, login+"@"+server_ip, "ls"])
Consider getting the key fingerprint from the console log of the booting instance (I know this is not entirely reliable, as not all images run cloudinit in the same way, and it will lead to more timeouts, but ssh connections without strict host key checking is always problematic, even if no secret data is sent over the connection).

2021-06-17 09:38 UTC, sebastianriese commented on src/manage.py
> +        keypair_file = os.getcwd() + '/' + keypair_name
Please use `pathlib.Path.cwd() / keypair_name` or at least `os.path.join` to piece together paths safely. Also using the cwd might not be ideal (although it is probably the most portable solution, I'd guess pyxdg doesn't work on windows or most non-Linux unices).

2021-06-17 09:38 UTC, sebastianriese commented on src/manage.py
> +    keypair_file = os.getcwd() + '/' + keypair_name
As above, use a proper method for joining paths.

2021-06-17 09:57 UTC, sebastianriese commented on src/manage.py
> +    test_process = subprocess.run(["ssh", "-o", "StrictHostKeyChecking no","-i", os.getcwd()+'/'+keypair_name, login+"@"+server_ip, "ls"])
Also replace the path joining with a proper method.

2021-06-17 11:47 UTC, sebastianriese commented on src/manage.py
> +    network_name = 'floating-IPv4'
At least the network name must be configurable. I guess we can get away with the solution of directly attaching the machine to the floating-IPv4 network (as the script needs admin credentials anyway, unless we want to create an own role for it and adapt the policy files of the services accordingly); but for sure the floating IP network will have different names (even in our own infrastructure).

Ideally all things about the test instance are configurable. (E.g. there may well be images that can't be booted on an S instance).

2021-06-18 09:23 UTC, tobfisch commented on src/manage.py
> +        return 'failure'
The function now returns `True`/ `False` instead of strings.

2021-06-18 09:26 UTC, tobfisch commented on src/manage.py
> +        keypair_file = os.getcwd() + '/' + keypair_name
I exchanged the functions, for creating the path `pathlib.Path.cwd()` will be used.

2021-06-18 09:26 UTC, tobfisch commented on src/manage.py
> +    keypair_file = os.getcwd() + '/' + keypair_name
Done.

2021-06-18 09:29 UTC, tobfisch commented on src/manage.py
> +    network_name = 'floating-IPv4'
I added CLI options to configure the used network and the flavor of the instance.

2021-06-18 09:34 UTC, sebastianriese commented on src/manage.py
> +                    uploaded_new_latest_image = False
I guess the logic is reversed here now. `test_image` returns true if the test was successful, so then uploaded_new_latest_image should remain true in that case?

2021-06-21 09:13 UTC, tobfisch commented on src/manage.py
> +                    uploaded_new_latest_image = False
You are right, the logic was reversed. 
It should now be correct again.

2021-06-21 09:54 UTC, sebastianriese approved these changes
Looks good to merge now.

2021-06-29 09:14 UTC, merged