Add support for the os_hidden property
tobfisch/openstack-image-manager pull request #3
Opened 2021-06-17 09:19 UTC by tobfisch

2021-06-17 10:08 UTC, sebastianriese requested changes

2021-06-17 10:08 UTC, sebastianriese commented on src/manage.py
> +                elif version not in sorted_versions[-3:]:
Shouldn't we set all but one versions of each image `os_hidden`, it seems to me that three are kept visible by the code.

2021-06-17 10:08 UTC, sebastianriese commented on src/manage.py
> +                            glance.images.update(cloud_image.id, **{property: image['meta'][property]})
Is this substitution safe? I see that it leads to errors for our boolean propery when it is `str`ed, but I guess the original code must have had a reason to `str` the property values.

(Also in the original code: Is one API call per changed property, instead of doing all the property changes with one roundrip?)

2021-06-17 15:32 UTC, tobfisch commented on src/manage.py
> +                elif version not in sorted_versions[-3:]:
I changed it so that only the newest version of an image is visible.

2021-06-17 15:33 UTC, tobfisch commented on src/manage.py
> +                            glance.images.update(cloud_image.id, **{property: image['meta'][property]})
I reverted the change and now the `os_hidden` property is set, similar to the `min_disk` property.

2021-06-21 09:55 UTC, sebastianriese approved these changes

2021-06-29 09:01 UTC, merged