Introduce update feature for the images.yaml
tobfisch/openstack-image-manager pull request #4
Opened 2021-06-25 08:25 UTC by tobfisch

2021-06-25 11:20 UTC, sebastianriese requested changes

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +    cfg.BoolOpt('latest', help='Only check the latest version', default=False)
The latest tag is declared here, but never used in the code. Please implement the functionality or remove the flag.

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +with open('etc/images.yml', "w") as fp:
Is it intentional, that this is written to the hardcoded path `etc/images.yml` while the input is controlled by the `--images` option (which defaults to the same path)?

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +    cfg.StrOpt('images', help='Path to the images.yml file', default='etc/images.yml'),
is it intentional that the default path is relative?

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +                daily_build_version = ''.join(re.findall(r'\d{4}-\d\d-\d\d', date[1])[0].split('-'))
Why `re.findall(...)[0]`? `re.search(...)[0]` should do the same and be more efficient (namely, find the first match, while `findall` looks for all matches).

You could also use grouping in the regex here to avoid having to post-process the result with `split`:
```
re.search(r'(\d{4})-(\d\d)-(\d\d)', input).groups()
```
(Note: the result is a tuple, so you may have to convert it to a list, or versions from other sources to tuples for the comparisons to work propery).

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +                        os_version = re.findall(image['regex'], date[0])[0]
Use `re.search(...)[0]` instead of `re.findall(...)[0]`. Perhaps even check if there is a match and return a useful error message if the regex does not match.

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +    return re.findall(r'[0-9]{8}', build_name)[0]
Use `re.search` instead of `re.findall`

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +                versions_on_url.add(re.findall(image['regex'], link.get('href'))[0])
Don't use `findall(...)[0]`.

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +    sorted_versions = natsorted(versions.keys())
The sorted_versions are never used. This means the `import natsorted` (and this line can go).

2021-06-25 11:20 UTC, sebastianriese commented on src/update_images.py
> +support_images = {
Please rename this to supported images. It might be preferable to load this as a config file instead of including it in the source.

2021-06-28 09:19 UTC, tobfisch commented on src/update_images.py
> +    cfg.BoolOpt('latest', help='Only check the latest version', default=False)
I removed the latest tag as it is not required.

2021-06-28 09:21 UTC, tobfisch commented on src/update_images.py
> +with open('etc/images.yml', "w") as fp:
No it was not intentional. 
I added an additional option, for the case that the old `etc/images.yml` should not be overwritten. 
However the option has `etc/images.yml` as default.

2021-06-28 09:24 UTC, tobfisch commented on src/update_images.py
> +                daily_build_version = ''.join(re.findall(r'\d{4}-\d\d-\d\d', date[1])[0].split('-'))
I exchanged all `findall`-calls with `search`.
I also used grouping as suggested, but still build a string via `''.join()`.

2021-06-28 09:33 UTC, tobfisch commented on src/update_images.py
> +                        os_version = re.findall(image['regex'], date[0])[0]
I exchanged the function calls and an error message is thrown if no match is found.

2021-06-28 09:34 UTC, tobfisch commented on src/update_images.py
> +    return re.findall(r'[0-9]{8}', build_name)[0]
Changed the function calls accordingly.

2021-06-28 09:34 UTC, tobfisch commented on src/update_images.py
> +                versions_on_url.add(re.findall(image['regex'], link.get('href'))[0])
Done.

2021-06-28 09:40 UTC, tobfisch commented on src/update_images.py
> +    sorted_versions = natsorted(versions.keys())
Removed both lines.

2021-06-28 14:07 UTC, tobfisch commented on src/update_images.py
> +support_images = {
I renamed it and also moved it to an yaml file which can be used as config file. 
(And an additional option to specify which file should be used as config.)

2021-06-29 08:33 UTC, tobfisch commented on src/update_images.py
> +    cfg.StrOpt('images', help='Path to the images.yml file', default='etc/images.yml'),
Yes, I adopted it from the other scripts. 
Is there a problem with a relative path as default?

2021-06-29 10:16 UTC, sebastianriese commented on src/update_images.py
> +    cfg.StrOpt('images', help='Path to the images.yml file', default='etc/images.yml'),
Not a problem, but it's weird. If you don't run from `/` the path will typically not exist (unless you make sure to create the parent directories. But if the others use a relative path for `etc` then we should just keep consistent (and think it's weird).

2021-06-29 10:27 UTC, sebastianriese requested changes

2021-06-29 10:27 UTC, sebastianriese commented on src/update_images.py
> +                        os_version = regex.search(date[0])[0]
The `[0]` will fail if there is no match found (because `regex.search` returns `None` then instead of a match object). The matched string can only be extracted in the `if os_version` branch below.

2021-06-29 10:27 UTC, sebastianriese commented on src/update_images.py
> +print(supported_images)
This should not be here. (Or it should at least be written as a debug log-message).

2021-07-01 06:53 UTC, tobfisch commented on src/update_images.py
> +                        os_version = regex.search(date[0])[0]
You are right, I have not thought of that. 
It should be fixed now.

2021-07-01 06:54 UTC, tobfisch commented on src/update_images.py
> +print(supported_images)
Yes, that was just a message for debugging. 
I removed the print command.

2021-07-01 07:57 UTC, tobfisch commented on src/update_images.py
> +    cfg.StrOpt('images', help='Path to the images.yml file', default='etc/images.yml'),
I think with the this default value the script was meant to be executed from the repository because an `etc`-directory exists here (https://github.com/tobfisch/openstack-image-manager/tree/master/etc). 
If it would be executed anywhere else, then this could cause problems.

2021-07-02 09:32 UTC, sebastianriese approved these changes

2021-07-07 14:33 UTC, merged